name: qr_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  floor: 1.0.1
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  url_launcher: ^6.0.0
  path_provider: ^2.0.2
  share: ^2.0.1
  image: ^3.0.1
  image_gallery_saver: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
